driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY'] %>
  security_group_ids:  <%= ENV['AWS_SECURITY_GROUPS'] %>
  region: <%= ENV['AWS_REGION'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>
  require_chef_omnibus: true
  subnet_id: <%= ENV['AWS_SUBNET'] %>
  associate_public_ip: false
  interface: private
  tags:
    OWNER: <%= ENV['AWS_OWNER_TAG'] %>
    Name: <%= ENV['AWS_NAME_TAG'] %>

provisioner:
  name: chef_zero
  attributes:
    appdynamics:
      version: '4.1.3.0'
      app_name: test-app
      tier_name: test-tier
      node_name: test-node
      controller:
        host: controller-host
        port: 443
        ssl: true
        user: controller-user
        accesskey: controller-accesskey
        http_proxy:
          host: http-proxy-host
          port: 2345
          user: http-proxy-user
          password_file: /tmp/foo/bar

transport:
  ssh_key: <%= ENV['SSH_KEY_PATH'] %><%= ENV['AWS_SSH_KEY'] %>.pem

platforms:
  - name: windows-2008r2
    driver:
      image_id: <%= ENV['AWS_WINDOWS2008R2_AMI_ID'] %>
      instance_type: <%= ENV['WINDOWS_INSTANCE_SIZE'] %>
      user_data: <%= ENV['WINDOWS_USER_DATA_PATH'] %>
    transport:
      name: winrm

suites:
  - name: remove_dotnet_agent
    run_list:
      - recipe[gd-test-helper::default]
      - recipe[iis]
      - recipe[test::install_agent]
      - recipe[appdynamics::remove_dotnet_agent]
    attributes:
    chef_client:
      config:
        log_level: :debug
